function ppx = vmlRemoveIsolatedPPX(im)
b = reshape(~isnan(im.ppx(:,1)),im.sz);
while 1
  no_neigh = ...
    ~(([b(:,2:end) false(im.sz(1),1)] | ...
    [false(im.sz(1),1) b(:,1:end-1)]) & ...
    ([b(2:end,:);false(1,im.sz(2))] | ...
    [false(1,im.sz(2));b(1:end-1,:)]));
  if ~any(b(no_neigh)), break; end
  b(no_neigh) = false;
end
ppx = im.ppx; ppx(~b,:) = nan;
